services:
  mongodb:
    image: mongo:latest
    container_name: loginflow_container
    ports:
      - "25017:25017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: server_container
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://admin:password@loginflow_container:27017/brandboost?authSource=admin
    depends_on:
      - mongodb
    volumes:
      - ./server:/usr/src/app
    restart: always

volumes:
  mongodb_data:
